### ISSUE TITLE
Dining hall opening/closing time

### ISSUE THREAD

**Issue by ChenJesse** [ChenJesse/diningAppV2#1]
Alter the models for a time opened field, where it scrapes for the hours its open

**Comment by suchanlee** [comment]
This probably doesn't need to be scraped -- scraping can be flaky so I would keep scraping to just the parts that actually need to be scraped. Things like this don't change so I would just manually create this.

**Comment by ChenJesse** [comment]
Hmm, but sometimes the opening/closing times change (holiday hours, summer hours, etc.) but I see your point...maybe we could just hard-code it in ourselves

**Comment by suchanlee** [comment]
For special hours, you can probably have a map mapping specific days to special hours? Not sure how it'll look but something like that may work

**Comment by ChenJesse** [comment]
Implemented primitively (hard-coded in)
